name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (leave empty for dry run)'
        required: false
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            arch: x64
          - os: windows-latest
            arch: arm64
          # macOS builds
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          # Linux builds
          - os: ubuntu-22.04
            arch: x64
          # Linux ARM64 (native)
          - os: ubuntu-22.04-arm
            arch: arm64

    name: Prebuild ${{ matrix.os }} (${{ matrix.arch }})
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          architecture: ${{ matrix.os == 'ubuntu-22.04-arm' && 'arm64' || ((matrix.os == 'windows-latest' && matrix.arch == 'arm64') && 'x64' || matrix.arch || 'x64') }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup MSBuild (Windows)
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3
        with:
          msbuild-architecture: x64

      - name: Setup Windows ARM64 cross-compilation
        if: matrix.os == 'windows-latest' && matrix.arch == 'arm64'
        run: |
          echo "npm_config_target_arch=arm64" >> $env:GITHUB_ENV
          echo "npm_config_target_platform=win32" >> $env:GITHUB_ENV
          echo "npm_config_arch=arm64" >> $env:GITHUB_ENV

      - name: Add setuptools (non-Windows)
        if: matrix.os != 'windows-latest'
        run: pip install setuptools

      - name: Override gnu target for older sysroot (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          mkdir -p "$HOME/.gyp"
          cat > "$HOME/.gyp/include.gypi" << 'EOF'
          {
            "target_defaults": {
              "conditions": [
                ["OS=='linux'", {
                  'cflags_cc!': [ '-std=gnu++20' ],
                  'cflags_cc': [ '-std=gnu++2a' ],
                }]
              ]
            }
          }
          EOF

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Create prebuilds
        shell: bash
        run: |
          echo "=== Building for ${{ matrix.os }} (${{ matrix.arch }}) ==="
          
          # Build only for the specific target architecture instead of using --all
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              echo "Building Windows ARM64 prebuild"
              npx prebuild --runtime napi --arch arm64 --verbose --strip
            else
              echo "Building Windows x64 prebuild" 
              npx prebuild --runtime napi --arch x64 --verbose --strip
            fi
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              echo "Building macOS ARM64 prebuild"
              npx prebuild --runtime napi --arch arm64 --verbose --strip
            else
              echo "Building macOS x64 prebuild"
              npx prebuild --runtime napi --arch x64 --verbose --strip  
            fi
          elif [[ "${{ matrix.os }}" == "ubuntu-22.04" ]]; then
            echo "Building Linux x64 prebuild"
            npx prebuild --runtime napi --arch x64 --verbose --strip
          elif [[ "${{ matrix.os }}" == "ubuntu-22.04-arm" ]]; then
            echo "Building Linux ARM64 prebuild" 
            npx prebuild --runtime napi --arch arm64 --verbose --strip
          else
            echo "Unknown OS/arch combination, falling back to default"
            npm run prebuild
          fi
          
          echo ""
          echo "Generated prebuilds:"
          find prebuilds/ -name "*.tar.gz" -exec basename {} \; 2>/dev/null || echo "No prebuilds found"
        env:
          npm_config_target_arch: ${{ (matrix.os == 'windows-latest' && matrix.arch == 'arm64') && 'arm64' || (matrix.arch == 'x86' && 'ia32' || matrix.arch) }}

      - name: Test prebuild
        # Skip test for cross-compilation scenarios
        if: ${{ !(matrix.os == 'windows-latest' && matrix.arch == 'arm64') }}
        run: |
          npm test
        env:
          npm_config_target_arch: ${{ matrix.arch == 'x86' && 'ia32' || matrix.arch }}

      - name: Upload prebuilds
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds/
          retention-days: 7

  release:
    needs: prebuild
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.tag
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Download all prebuilds
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Organize prebuilds
        run: |
          mkdir -p prebuilds
          
          echo "=== Organizing prebuilds from artifacts ==="
          echo "Available artifact directories:"
          ls -la artifacts/
          echo ""
          
          # Process each artifact directory separately to ensure we don't lose any files
          for artifact_dir in artifacts/*/; do
            if [ -d "$artifact_dir" ]; then
              artifact_name=$(basename "$artifact_dir")
              echo "Processing artifact: $artifact_name"
              
              # List contents of this artifact
              echo "  Contents:"
              find "$artifact_dir" -type f -name "*.tar.gz" | while read file; do
                echo "    $(basename "$file")"
              done
              
              # Copy files, checking for duplicates
              find "$artifact_dir" -name "*.tar.gz" | while read file; do
                filename=$(basename "$file")
                if [ -f "prebuilds/$filename" ]; then
                  echo "  ⚠️  CONFLICT: $filename already exists!"
                  echo "     This suggests multiple artifacts contain files with the same name"
                  echo "     Artifact: $artifact_name"
                  echo "     Keeping both files for investigation..."
                  cp "$file" "prebuilds/${artifact_name}-${filename}"
                else
                  echo "  ✅ Copying: $filename"
                  cp "$file" "prebuilds/"
                fi
              done
              echo ""
            fi
          done
          
          echo "=== Final prebuilds directory ==="
          ls -la prebuilds/
          echo ""
          total_files=$(find prebuilds/ -name "*.tar.gz" | wc -l)
          echo "Total prebuild files: $total_files"
          if [ "$total_files" -ne 6 ]; then
            echo "⚠️  WARNING: Expected 6 prebuild files but found $total_files"
            echo "This indicates the naming conflict issue persists"
          else
            echo "✅ Success: Found all 6 expected prebuild files"
          fi

      - name: Get release info
        id: release_info
        run: |
          if [ "${{ github.event.inputs.tag }}" != "" ]; then
            TAG_NAME="${{ github.event.inputs.tag }}"
            echo "This is a manual release for tag: $TAG_NAME"
          else
            TAG_NAME="${GITHUB_REF#refs/tags/}"
          fi
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "release_name=vscode-policy-watcher $TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_info.outputs.tag_name }}
          release_name: ${{ steps.release_info.outputs.release_name }}
          body: |
            ## Changes
            
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
            
            ## Platform-specific binaries
            
            This release includes prebuilt binaries for:
            - Windows (x64, arm64)
            - macOS (x64, arm64) 
            - Linux (x64, arm64)
            
            The binaries will be automatically downloaded when installing via npm.
          draft: false
          prerelease: ${{ contains(steps.release_info.outputs.tag_name, '-') }}

      - name: Upload Release Assets
        run: |
          echo "=== Uploading prebuilds to release ==="
          
          # Count total files before upload
          total_files=$(find prebuilds/ -name "*.tar.gz" | wc -l)
          echo "Total files to upload: $total_files"
          
          if [ "$total_files" -ne 6 ]; then
            echo "⚠️  WARNING: Expected 6 files but found $total_files"
            echo "This may indicate the naming conflict was not fully resolved"
            echo "Files available for upload:"
            ls -la prebuilds/
          fi
          
          # Upload each file
          uploaded_count=0
          for file in prebuilds/*.tar.gz; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              echo "📦 Uploading: $filename"
              if gh release upload "${{ steps.release_info.outputs.tag_name }}" "$file" --clobber; then
                echo "  ✅ Successfully uploaded: $filename"
                uploaded_count=$((uploaded_count + 1))
              else
                echo "  ❌ Failed to upload: $filename"
              fi
            fi
          done
          
          echo ""
          echo "=== Upload Summary ==="
          echo "Files uploaded: $uploaded_count"
          echo "Files expected: 6"
          
          if [ "$uploaded_count" -eq 6 ]; then
            echo "✅ SUCCESS: All 6 prebuilds uploaded successfully!"
          else
            echo "❌ ISSUE: Only $uploaded_count out of 6 files uploaded"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm (if not manual)
        if: startsWith(github.ref, 'refs/tags/') && !github.event.inputs.tag
        run: |
          npm ci --ignore-scripts
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}